name: "Perform static analysis"
description: "Perform static analysis"
inputs:
  sonar_organisation_key:
    description: "Sonar organisation key, used to identify the project"
    required: false
  sonar_project_key:
    description: "Sonar project key, used to identify the project"
    required: false
  sonar_token:
    description: "Sonar token, the API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: |
        if [[ -n "$SONAR_TOKEN" ]]; then
          echo "secret_exist=true" >> "$GITHUB_OUTPUT"
        else
          echo "secret_exist=false" >> "$GITHUB_OUTPUT"
        fi
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      env:
        SONAR_ORGANISATION_KEY: ${{ inputs.sonar_organisation_key }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar_project_key }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: |
        export BRANCH_NAME=${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's#refs/heads/##')}
        ./scripts/reports/perform-static-analysis.sh
